// webapp/src/components/ConditionBuilder.tsx
// EPIC06 — Approval Matrix: Condition Builder (Slice D của refactor,
// docs/research/approval-matrix-refactor-plan.md §4.D).
//
// Trình soạn CÂY điều kiện AND/OR động thay cho 4 trường cứng cũ. Đệ quy: mỗi
// nhóm tự quản mảng items (leaf hoặc nhóm con) + toán tử logic. Control giá trị
// render theo `type` của biến (registry) — người nghiệp vụ không chạm cấu trúc.

import {
  Button,
  Input,
  InputNumber,
  Segmented,
  Select,
  Space,
  Tag,
  Typography,
} from 'antd'
import {
  DeleteOutlined,
  PlusOutlined,
  BranchesOutlined,
} from '@ant-design/icons'
import {
  OPERATORS,
  describeConditionTree,
  group,
  type ConditionGroup,
  type ConditionLeaf,
  type ConditionNode,
  type ConditionOperator,
} from '../data/approvalConditions'
import {
  APPROVAL_VARIABLES,
  variableDef,
  describeHelpers,
} from '../data/approvalVariableRegistry'

const { Text } = Typography

const OP_META = new Map(OPERATORS.map((o) => [o.op, o]))
const FIELD_OPTIONS = APPROVAL_VARIABLES.map((v) => ({
  value: v.key,
  label: `${v.label}${v.simulated ? '' : ' ·'}`,
}))

/** Leaf mặc định khi thêm điều kiện mới: biến đầu tiên + toán tử đầu tiên của nó. */
function defaultLeaf(): ConditionLeaf {
  const v = APPROVAL_VARIABLES[0]
  return { kind: 'condition', field: v.key, operator: v.operators[0] }
}

function isUnary(op: ConditionOperator): boolean {
  return OP_META.get(op)?.arity === 'unary'
}

// ── Ô nhập giá trị theo kiểu biến ─────────────────────────────────────────────
function ValueControl({
  field,
  operator,
  value,
  valueTo,
  onChange,
}: {
  field: string
  operator: ConditionOperator
  value: unknown
  valueTo: unknown
  onChange: (patch: { value?: unknown; valueTo?: unknown }) => void
}) {
  if (isUnary(operator)) return null
  const def = variableDef(field)
  const type = def?.type ?? 'string'

  // `in` trên enum → chọn nhiều
  if (operator === 'in' && def?.options) {
    return (
      <Select
        mode="multiple"
        style={{ minWidth: 200 }}
        placeholder="Chọn giá trị"
        value={Array.isArray(value) ? (value as string[]) : []}
        onChange={(v) => onChange({ value: v })}
        options={def.options}
      />
    )
  }
  if (type === 'enum' || type === 'multiEnum') {
    return (
      <Select
        style={{ minWidth: 180 }}
        placeholder="Chọn giá trị"
        value={(value as string) ?? undefined}
        onChange={(v) => onChange({ value: v })}
        options={def?.options ?? []}
      />
    )
  }
  if (type === 'boolean') {
    return (
      <Select
        style={{ width: 110 }}
        value={value === undefined ? undefined : Boolean(value)}
        placeholder="—"
        onChange={(v) => onChange({ value: v })}
        options={[
          { value: true, label: 'Có' },
          { value: false, label: 'Không' },
        ]}
      />
    )
  }
  if (type === 'number') {
    if (operator === 'between') {
      return (
        <Space size={4}>
          <InputNumber
            style={{ width: 150 }}
            placeholder="Từ"
            value={value as number}
            onChange={(v) => onChange({ value: v ?? undefined })}
            formatter={(v) => (v == null ? '' : new Intl.NumberFormat('vi-VN').format(Number(v)))}
            parser={(s) => Number((s ?? '').replace(/\D/g, ''))}
          />
          <Text type="secondary">–</Text>
          <InputNumber
            style={{ width: 150 }}
            placeholder="Đến"
            value={valueTo as number}
            onChange={(v) => onChange({ valueTo: v ?? undefined })}
            formatter={(v) => (v == null ? '' : new Intl.NumberFormat('vi-VN').format(Number(v)))}
            parser={(s) => Number((s ?? '').replace(/\D/g, ''))}
          />
        </Space>
      )
    }
    return (
      <InputNumber
        style={{ width: 180 }}
        placeholder="Giá trị"
        value={value as number}
        onChange={(v) => onChange({ value: v ?? undefined })}
        formatter={(v) => (v == null ? '' : new Intl.NumberFormat('vi-VN').format(Number(v)))}
        parser={(s) => Number((s ?? '').replace(/\D/g, ''))}
      />
    )
  }
  // string / date
  return (
    <Input
      style={{ width: 180 }}
      placeholder="Giá trị"
      value={(value as string) ?? ''}
      onChange={(e) => onChange({ value: e.target.value })}
    />
  )
}

// ── Một dòng điều kiện (leaf) ─────────────────────────────────────────────────
function LeafRow({
  node,
  onChange,
  onRemove,
}: {
  node: ConditionLeaf
  onChange: (next: ConditionLeaf) => void
  onRemove: () => void
}) {
  const def = variableDef(node.field)
  const opOptions = (def?.operators ?? []).map((op) => ({
    value: op,
    label: OP_META.get(op)?.symbol ?? op,
  }))
  return (
    <Space wrap style={{ marginBottom: 8 }}>
      <Select
        style={{ minWidth: 180 }}
        showSearch
        optionFilterProp="label"
        value={node.field}
        onChange={(field) => {
          const nd = variableDef(field)
          // Đổi biến → reset toán tử + giá trị theo biến mới
          onChange({ kind: 'condition', field, operator: nd?.operators[0] ?? 'eq' })
        }}
        options={FIELD_OPTIONS}
      />
      <Select
        style={{ minWidth: 120 }}
        value={node.operator}
        onChange={(operator) =>
          onChange({ ...node, operator, value: undefined, valueTo: undefined })
        }
        options={opOptions}
      />
      <ValueControl
        field={node.field}
        operator={node.operator}
        value={node.value}
        valueTo={node.valueTo}
        onChange={(patch) => onChange({ ...node, ...patch })}
      />
      <Button type="text" danger size="small" icon={<DeleteOutlined />} onClick={onRemove} />
    </Space>
  )
}

// ── Trình soạn một nhóm (đệ quy) ──────────────────────────────────────────────
function GroupEditor({
  value,
  onChange,
  isRoot,
  onRemove,
}: {
  value: ConditionGroup
  onChange: (next: ConditionGroup) => void
  isRoot?: boolean
  onRemove?: () => void
}) {
  const setItem = (i: number, node: ConditionNode) =>
    onChange({ ...value, items: value.items.map((it, idx) => (idx === i ? node : it)) })
  const removeItem = (i: number) =>
    onChange({ ...value, items: value.items.filter((_, idx) => idx !== i) })
  const addLeaf = () => onChange({ ...value, items: [...value.items, defaultLeaf()] })
  const addGroup = () =>
    onChange({ ...value, items: [...value.items, group('AND', [defaultLeaf()])] })

  return (
    <div
      style={{
        border: '1px solid var(--vht-border, #eee)',
        borderRadius: 8,
        padding: 12,
        background: isRoot ? 'transparent' : 'var(--vht-surface-2, #fafafa)',
      }}
    >
      <Space style={{ marginBottom: 8, width: '100%', justifyContent: 'space-between' }}>
        <Space>
          <Segmented
            size="small"
            value={value.logic}
            onChange={(v) => onChange({ ...value, logic: v as 'AND' | 'OR' })}
            options={[
              { value: 'AND', label: 'TẤT CẢ (VÀ)' },
              { value: 'OR', label: 'MỘT TRONG (HOẶC)' },
            ]}
          />
          {value.items.length === 0 && <Tag>bất kỳ hồ sơ</Tag>}
        </Space>
        {!isRoot && (
          <Button type="text" danger size="small" icon={<DeleteOutlined />} onClick={onRemove}>
            Xoá nhóm
          </Button>
        )}
      </Space>

      <div style={{ paddingLeft: 4 }}>
        {value.items.map((it, i) =>
          it.kind === 'condition' ? (
            <LeafRow
              key={i}
              node={it}
              onChange={(n) => setItem(i, n)}
              onRemove={() => removeItem(i)}
            />
          ) : (
            <div key={i} style={{ marginBottom: 8 }}>
              <GroupEditor
                value={it}
                onChange={(n) => setItem(i, n)}
                onRemove={() => removeItem(i)}
              />
            </div>
          ),
        )}
      </div>

      <Space>
        <Button size="small" icon={<PlusOutlined />} onClick={addLeaf}>
          Thêm điều kiện
        </Button>
        <Button size="small" icon={<BranchesOutlined />} onClick={addGroup}>
          Thêm nhóm con
        </Button>
      </Space>
    </div>
  )
}

/**
 * Trình soạn cây điều kiện của một luật. `value` là nhóm gốc; nhóm rỗng = khớp mọi
 * hồ sơ. Hiển thị preview tiếng Việt bên dưới để người nghiệp vụ đọc lại.
 */
export default function ConditionBuilder({
  value,
  onChange,
}: {
  value: ConditionGroup
  onChange: (next: ConditionGroup) => void
}) {
  return (
    <div>
      <GroupEditor value={value} onChange={onChange} isRoot />
      <div style={{ marginTop: 8 }}>
        <Text type="secondary" style={{ fontSize: 12 }}>
          Diễn giải:{' '}
        </Text>
        <Text style={{ fontSize: 12 }}>{describeConditionTree(value, describeHelpers)}</Text>
      </div>
    </div>
  )
}

// frontend-angular/src/app/shared/condition-builder/condition-builder.ts
import { Component, computed, input, output } from '@angular/core';
import { FormsModule } from '@angular/forms';

import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzIconModule } from 'ng-zorro-antd/icon';
import { NzInputModule } from 'ng-zorro-antd/input';
import { NzInputNumberModule } from 'ng-zorro-antd/input-number';
import { NzSegmentedModule } from 'ng-zorro-antd/segmented';
import { NzSelectModule } from 'ng-zorro-antd/select';
import { NzTagModule } from 'ng-zorro-antd/tag';
import { NzTypographyModule } from 'ng-zorro-antd/typography';

import {
  OPERATORS,
  describeConditionTree,
  group,
  type ConditionGroup,
  type ConditionLeaf,
  type ConditionNode,
  type ConditionOperator,
} from '../../core/models/approval-conditions';
import { APPROVAL_VARIABLES, describeHelpers, variableDef } from '../../core/models/approval-variable-registry';

const OP_META = new Map(OPERATORS.map((o) => [o.op, o]));
const FIELD_OPTIONS = APPROVAL_VARIABLES.map((v) => ({ value: v.key, label: v.label }));

type ValueControlKind = 'none' | 'multiSelect' | 'select' | 'boolean' | 'numberRange' | 'number' | 'text';

/** Leaf mặc định khi thêm điều kiện mới: biến đầu tiên + toán tử đầu tiên của nó. */
function defaultLeaf(): ConditionLeaf {
  const v = APPROVAL_VARIABLES[0];
  return { kind: 'condition', field: v.key, operator: v.operators[0] };
}

function isUnary(op: ConditionOperator): boolean {
  return OP_META.get(op)?.arity === 'unary';
}

function controlKindFor(leafNode: ConditionLeaf): ValueControlKind {
  if (isUnary(leafNode.operator)) return 'none';
  const def = variableDef(leafNode.field);
  const type = def?.type ?? 'string';
  if (leafNode.operator === 'in' && def?.options) return 'multiSelect';
  if (type === 'enum' || type === 'multiEnum') return 'select';
  if (type === 'boolean') return 'boolean';
  if (type === 'number') return leafNode.operator === 'between' ? 'numberRange' : 'number';
  return 'text';
}

/**
 * Trình soạn cây điều kiện AND/OR của một luật Ma trận phê duyệt. Port của
 * webapp/src/components/ConditionBuilder.tsx (`ConditionBuilder` + `GroupEditor` +
 * `LeafRow` + `ValueControl` gộp lại — D17 Angular migration).
 *
 * Đệ quy: một instance đại diện cho một nhóm (AND/OR); nhóm con tái dùng chính
 * component này qua `[isRoot]="false"`, tự chứa nút "Xoá nhóm" gọi `removeGroup`
 * — logic xoá (splice khỏi mảng items) do component CHA (đang lặp `items`) thực
 * hiện, y hệt boundary `onRemove` của React.
 */
@Component({
  selector: 'app-condition-builder',
  imports: [
    ConditionBuilderComponent,
    FormsModule,
    NzButtonModule,
    NzIconModule,
    NzInputModule,
    NzInputNumberModule,
    NzSegmentedModule,
    NzSelectModule,
    NzTagModule,
    NzTypographyModule,
  ],
  templateUrl: './condition-builder.html',
  styleUrl: './condition-builder.scss',
})
export class ConditionBuilderComponent {
  readonly value = input.required<ConditionGroup>();
  readonly isRoot = input<boolean>(true);

  readonly valueChange = output<ConditionGroup>();
  /** Chỉ phát khi `isRoot()` là false — nhóm cha xoá item này khỏi mảng items của nó. */
  readonly removeGroup = output<void>();

  readonly fieldOptions = FIELD_OPTIONS;
  readonly logicOptions = [
    { label: 'TẤT CẢ (VÀ)', value: 'AND' },
    { label: 'MỘT TRONG (HOẶC)', value: 'OR' },
  ];

  readonly preview = computed(() => describeConditionTree(this.value(), describeHelpers));

  setLogic(logic: string | number): void {
    this.valueChange.emit({ ...this.value(), logic: logic as 'AND' | 'OR' });
  }

  addLeaf(): void {
    this.valueChange.emit({ ...this.value(), items: [...this.value().items, defaultLeaf()] });
  }

  addGroup(): void {
    this.valueChange.emit({ ...this.value(), items: [...this.value().items, group('AND', [defaultLeaf()])] });
  }

  setItem(i: number, node: ConditionNode): void {
    this.valueChange.emit({
      ...this.value(),
      items: this.value().items.map((it, idx) => (idx === i ? node : it)),
    });
  }

  removeItem(i: number): void {
    this.valueChange.emit({ ...this.value(), items: this.value().items.filter((_, idx) => idx !== i) });
  }

  operatorOptions(leafNode: ConditionLeaf): { value: ConditionOperator; label: string }[] {
    const def = variableDef(leafNode.field);
    return (def?.operators ?? []).map((op) => ({ value: op, label: OP_META.get(op)?.symbol ?? op }));
  }

  controlKind(leafNode: ConditionLeaf): ValueControlKind {
    return controlKindFor(leafNode);
  }

  selectOptions(leafNode: ConditionLeaf): { value: string; label: string }[] {
    return variableDef(leafNode.field)?.options ?? [];
  }

  onFieldChange(i: number, field: string): void {
    const def = variableDef(field);
    this.setItem(i, { kind: 'condition', field, operator: def?.operators[0] ?? 'eq' });
  }

  onOperatorChange(i: number, leafNode: ConditionLeaf, operator: ConditionOperator): void {
    this.setItem(i, { ...leafNode, operator, value: undefined, valueTo: undefined });
  }

  onValueChange(i: number, leafNode: ConditionLeaf, patch: { value?: unknown; valueTo?: unknown }): void {
    this.setItem(i, { ...leafNode, ...patch });
  }

  stringValue(leafNode: ConditionLeaf): string | null {
    return typeof leafNode.value === 'string' ? leafNode.value : null;
  }

  multiValue(leafNode: ConditionLeaf): string[] {
    return Array.isArray(leafNode.value) ? (leafNode.value as string[]) : [];
  }

  boolValue(leafNode: ConditionLeaf): boolean | null {
    return leafNode.value === undefined ? null : Boolean(leafNode.value);
  }

  numberValue(leafNode: ConditionLeaf): number | null {
    return typeof leafNode.value === 'number' ? leafNode.value : null;
  }

  numberToValue(leafNode: ConditionLeaf): number | null {
    return typeof leafNode.valueTo === 'number' ? leafNode.valueTo : null;
  }

  formatVnd(value: number): string {
    return new Intl.NumberFormat('vi-VN').format(value);
  }

  parseVnd(value: string): number {
    return Number((value ?? '').replace(/\D/g, ''));
  }

  isLeaf(node: ConditionNode): node is ConditionLeaf {
    return node.kind === 'condition';
  }

  asGroup(node: ConditionNode): ConditionGroup {
    return node as ConditionGroup;
  }
}
