// webapp/src/components/ServiceTaskExecutionDrawer.tsx
﻿import { useMemo, useState, type CSSProperties } from 'react'
import {
  Alert,
  Button,
  Descriptions,
  Drawer,
  Empty,
  Input,
  Modal,
  Space,
  Tag,
  Timeline,
  Typography,
} from 'antd'
import {
  CheckCircleOutlined,
  ClockCircleOutlined,
  ExclamationCircleOutlined,
  RetweetOutlined,
  ToolOutlined,
} from '@ant-design/icons'
import {
  SERVICE_TASK_EXECUTION_STATUS_META,
  type ServiceTaskConfigVersion,
  type ServiceTaskDefinition,
  type ServiceTaskExecutionLog,
} from '../data/serviceTasks'
import { StatusTag } from './ui'

const { Text } = Typography

const MONO_STYLE = {
  fontFamily: "'Fira Code', ui-monospace, SFMono-Regular, Consolas, monospace",
  fontSize: 12,
} satisfies CSSProperties

function pretty(value: unknown): string {
  return JSON.stringify(value ?? {}, null, 2)
}

function JsonBlock({ value }: { value?: Record<string, unknown> }) {
  if (!value) return <Empty description="KhÃ´ng cÃ³ dá»¯ liá»‡u." />
  return (
    <pre
      style={{
        ...MONO_STYLE,
        margin: 0,
        padding: 12,
        maxHeight: 260,
        overflow: 'auto',
        whiteSpace: 'pre-wrap',
        wordBreak: 'break-word',
        background: '#f6f8fa',
        border: '1px solid var(--vht-border)',
        borderRadius: 6,
      }}
    >
      {pretty(value)}
    </pre>
  )
}

function formatDuration(durationMs?: number): string {
  if (durationMs === undefined) return '-'
  if (durationMs < 1000) return `${durationMs} ms`
  return `${(durationMs / 1000).toFixed(durationMs >= 10000 ? 0 : 1)} s`
}

interface ServiceTaskExecutionDrawerProps {
  open: boolean
  log?: ServiceTaskExecutionLog
  definition?: ServiceTaskDefinition
  version?: ServiceTaskConfigVersion
  onClose: () => void
  onRetry: (logId: string) => void
  onManualResolve: (logId: string, note: string) => void
}

export default function ServiceTaskExecutionDrawer({
  open,
  log,
  definition,
  version,
  onClose,
  onRetry,
  onManualResolve,
}: ServiceTaskExecutionDrawerProps) {
  const [manualNote, setManualNote] = useState('')
  const statusMeta = log ? SERVICE_TASK_EXECUTION_STATUS_META[log.status] : undefined

  const timelineItems = useMemo(() => {
    if (!log) return []
    const attempts = Array.from({ length: Math.max(log.attemptNo, 1) }, (_, index) => index + 1)
    return attempts.map((attempt) => {
      const isCurrent = attempt === log.attemptNo
      const failed = log.status === 'FAILED' && isCurrent
      const retrying = log.status === 'RETRYING' && isCurrent
      const success = log.status === 'SUCCESS' && isCurrent
      return {
        color: failed ? 'red' : retrying ? 'orange' : success ? 'green' : 'blue',
        dot: failed ? (
          <ExclamationCircleOutlined />
        ) : retrying ? (
          <RetweetOutlined />
        ) : success ? (
          <CheckCircleOutlined />
        ) : (
          <ClockCircleOutlined />
        ),
        children: (
          <Space direction="vertical" size={2}>
            <Text strong>Attempt {attempt}</Text>
            <Text type="secondary">
              {isCurrent
                ? `${log.startedAt}${log.finishedAt ? ` -> ${log.finishedAt}` : ''}`
                : 'Láº§n thá»­ trÆ°á»›c trong cÃ¹ng incident mock'}
            </Text>
            {failed && log.errorMessage ? <Text type="danger">{log.errorMessage}</Text> : null}
          </Space>
        ),
      }
    })
  }, [log])

  const confirmManualResolve = () => {
    if (!log) return
    let note = manualNote
    Modal.confirm({
      title: 'Manual resolve service task?',
      content: (
        <Space direction="vertical" size={8} style={{ width: '100%' }}>
          <Text>Ghi chÃº sáº½ Ä‘Æ°á»£c lÆ°u vÃ o execution log mock vÃ  audit in-memory.</Text>
          <Input.TextArea
            rows={4}
            defaultValue={manualNote}
            placeholder="Nháº­p lÃ½ do xá»­ lÃ½ tay"
            onChange={(event) => {
              note = event.target.value
              setManualNote(event.target.value)
            }}
          />
        </Space>
      ),
      okText: 'Manual resolve',
      cancelText: 'Há»§y',
      onOk: () => {
        onManualResolve(log.id, note.trim() || 'ÄÃ£ xá»­ lÃ½ tay bá»Ÿi ngÆ°á»i váº­n hÃ nh.')
        setManualNote('')
      },
    })
  }

  return (
    <Drawer
      title={log ? `Execution log ${log.processInstanceKey}` : 'Execution log'}
      open={open}
      onClose={onClose}
      width={760}
      destroyOnClose
      extra={
        log ? (
          <Space>
            <Button
              icon={<RetweetOutlined />}
              disabled={log.status !== 'FAILED'}
              onClick={() => onRetry(log.id)}
            >
              Retry
            </Button>
            <Button
              icon={<ToolOutlined />}
              disabled={log.status !== 'FAILED' && log.status !== 'RETRYING'}
              onClick={confirmManualResolve}
            >
              Manual resolve
            </Button>
          </Space>
        ) : null
      }
    >
      {!log || !statusMeta ? (
        <Empty description="ChÆ°a chá»n execution log." />
      ) : (
        <Space direction="vertical" size={16} style={{ width: '100%' }}>
          <Alert
            type={log.status === 'FAILED' ? 'error' : log.status === 'SUCCESS' ? 'success' : 'info'}
            showIcon
            message={
              <Space wrap>
                <Text strong>{log.taskName}</Text>
                <StatusTag color={statusMeta.color} label={statusMeta.label} />
                {log.incidentId ? <Tag color="error">{log.incidentId}</Tag> : null}
              </Space>
            }
            description={`${log.processCode} v${log.processVersion} / ${log.taskDefinitionKey}`}
          />

          <Descriptions size="small" bordered column={1}>
            <Descriptions.Item label="Instance key">{log.processInstanceKey}</Descriptions.Item>
            <Descriptions.Item label="Definition">
              {definition ? (
                <Space wrap>
                  <Text strong>{definition.name}</Text>
                  <Tag>{definition.code}</Tag>
                  <Tag>{definition.typeCode}</Tag>
                </Space>
              ) : (
                <Text type="secondary">KhÃ´ng tÃ¬m tháº¥y definition</Text>
              )}
            </Descriptions.Item>
            <Descriptions.Item label="Config version">
              {version ? (
                <Space wrap>
                  <Tag color={version.status === 'ACTIVE' ? 'green' : 'blue'}>v{version.versionNo}</Tag>
                  <Tag>{version.status}</Tag>
                  <Text type="secondary">{version.changeNote}</Text>
                </Space>
              ) : (
                <Tag>v{log.configVersionNo}</Tag>
              )}
            </Descriptions.Item>
            <Descriptions.Item label="Thá»i gian">
              {log.startedAt} {'->'} {log.finishedAt ?? 'Ä‘ang xá»­ lÃ½'} ({formatDuration(log.durationMs)})
            </Descriptions.Item>
            <Descriptions.Item label="Worker">{log.actor ?? '-'}</Descriptions.Item>
            <Descriptions.Item label="Error">
              {log.errorCode ? (
                <Space direction="vertical" size={2}>
                  <Tag color="error">{log.errorCode}</Tag>
                  <Text>{log.errorMessage}</Text>
                </Space>
              ) : (
                <Text type="secondary">KhÃ´ng cÃ³ lá»—i.</Text>
              )}
            </Descriptions.Item>
          </Descriptions>

          <Descriptions size="small" bordered column={1}>
            <Descriptions.Item label="Error policy Ã¡p dá»¥ng">
              {version ? (
                <Space wrap>
                  <Tag>timeout {version.errorPolicy.timeoutMs} ms</Tag>
                  <Tag>retry {version.errorPolicy.maxRetry}</Tag>
                  <Tag>delay {version.errorPolicy.retryDelayMs} ms</Tag>
                  <Tag>{version.errorPolicy.retryBackoff}</Tag>
                  <Tag>{version.errorPolicy.onFailure}</Tag>
                </Space>
              ) : (
                <Text type="secondary">KhÃ´ng cÃ³ snapshot policy trong mock log.</Text>
              )}
            </Descriptions.Item>
            <Descriptions.Item label="LiÃªn káº¿t mock">
              <Space wrap>
                <Tag color="blue">Process {log.processCode}</Tag>
                <Tag color="purple">Job {log.taskDefinitionKey}</Tag>
                {log.incidentId ? <Tag color="red">Incident {log.incidentId}</Tag> : null}
              </Space>
            </Descriptions.Item>
          </Descriptions>

          <Space direction="vertical" size={8} style={{ width: '100%' }}>
            <Text strong>Request summary masked</Text>
            <JsonBlock value={log.requestSummary} />
          </Space>

          <Space direction="vertical" size={8} style={{ width: '100%' }}>
            <Text strong>Response summary masked</Text>
            <JsonBlock value={log.responseSummary} />
          </Space>

          <Space direction="vertical" size={8} style={{ width: '100%' }}>
            <Text strong>Timeline attempt</Text>
            <Timeline items={timelineItems} />
          </Space>
        </Space>
      )}
    </Drawer>
  )
}

// frontend-angular/src/app/shared/service-task-execution-drawer/service-task-execution-drawer.ts
import { Component, computed, input, output, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';

import { NzAlertModule } from 'ng-zorro-antd/alert';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzDescriptionsModule } from 'ng-zorro-antd/descriptions';
import { NzDrawerModule } from 'ng-zorro-antd/drawer';
import { NzEmptyModule } from 'ng-zorro-antd/empty';
import { NzIconModule } from 'ng-zorro-antd/icon';
import { NzInputModule } from 'ng-zorro-antd/input';
import { NzModalModule } from 'ng-zorro-antd/modal';
import { NzTagModule } from 'ng-zorro-antd/tag';
import { NzTimelineModule } from 'ng-zorro-antd/timeline';
import { NzTypographyModule } from 'ng-zorro-antd/typography';

import {
  SERVICE_TASK_EXECUTION_STATUS_META,
  type ServiceTaskConfigVersion,
  type ServiceTaskDefinition,
  type ServiceTaskExecutionLog,
} from '../../core/models/service-task';

// Port của webapp/src/components/ServiceTaskExecutionDrawer.tsx — drawer chi tiết
// execution log ở tab "Log thực thi": timeline attempt, request/response summary
// masked, Retry/Manual resolve. Bản gốc bị lỗi encoding mojibake ở nhiều chuỗi
// tiếng Việt (vd. "KhÃ´ng cÃ³ dá»¯ liá»‡u.") — port này gõ lại đúng UTF-8 từ ngữ cảnh,
// không copy nguyên văn chuỗi hỏng.

function pretty(value: unknown): string {
  return JSON.stringify(value ?? {}, null, 2);
}

function formatDuration(durationMs?: number): string {
  if (durationMs === undefined) return '-';
  if (durationMs < 1000) return `${durationMs} ms`;
  return `${(durationMs / 1000).toFixed(durationMs >= 10000 ? 0 : 1)} s`;
}

interface TimelineItem {
  color: string;
  icon: string;
  attempt: number;
  isCurrent: boolean;
  timeText: string;
  errorMessage?: string;
}

@Component({
  selector: 'app-service-task-execution-drawer',
  imports: [
    FormsModule,
    NzAlertModule,
    NzButtonModule,
    NzDescriptionsModule,
    NzDrawerModule,
    NzEmptyModule,
    NzIconModule,
    NzInputModule,
    NzModalModule,
    NzTagModule,
    NzTimelineModule,
    NzTypographyModule,
  ],
  templateUrl: './service-task-execution-drawer.html',
  styleUrl: './service-task-execution-drawer.scss',
})
export class ServiceTaskExecutionDrawer {
  readonly open = input(false);
  readonly log = input<ServiceTaskExecutionLog | undefined>(undefined);
  readonly definition = input<ServiceTaskDefinition | undefined>(undefined);
  readonly version = input<ServiceTaskConfigVersion | undefined>(undefined);
  readonly closed = output<void>();
  readonly retry = output<string>();
  readonly manualResolve = output<{ logId: string; note: string }>();

  readonly statusMeta = SERVICE_TASK_EXECUTION_STATUS_META;
  readonly manualNote = signal('');
  readonly manualResolveOpen = signal(false);

  readonly currentStatusMeta = computed(() => {
    const log = this.log();
    return log ? this.statusMeta[log.status] : undefined;
  });

  readonly timelineItems = computed<TimelineItem[]>(() => {
    const log = this.log();
    if (!log) return [];
    const attempts = Array.from({ length: Math.max(log.attemptNo, 1) }, (_, index) => index + 1);
    return attempts.map((attempt) => {
      const isCurrent = attempt === log.attemptNo;
      const failed = log.status === 'FAILED' && isCurrent;
      const retrying = log.status === 'RETRYING' && isCurrent;
      const success = log.status === 'SUCCESS' && isCurrent;
      return {
        color: failed ? 'red' : retrying ? 'orange' : success ? 'green' : 'blue',
        icon: failed ? 'exclamation-circle' : retrying ? 'retweet' : success ? 'check-circle' : 'clock-circle',
        attempt,
        isCurrent,
        timeText: isCurrent
          ? `${log.startedAt}${log.finishedAt ? ` -> ${log.finishedAt}` : ''}`
          : 'Lần thử trước trong cùng incident mock',
        errorMessage: failed ? log.errorMessage : undefined,
      };
    });
  });

  prettyRequest(): string {
    return pretty(this.log()?.requestSummary);
  }

  prettyResponse(): string {
    return pretty(this.log()?.responseSummary);
  }

  formatDuration(durationMs?: number): string {
    return formatDuration(durationMs);
  }

  close(): void {
    this.closed.emit();
  }

  onRetry(): void {
    const log = this.log();
    if (log) this.retry.emit(log.id);
  }

  openManualResolve(): void {
    this.manualNote.set('');
    this.manualResolveOpen.set(true);
  }

  closeManualResolve(): void {
    this.manualResolveOpen.set(false);
  }

  confirmManualResolve(): void {
    const log = this.log();
    if (!log) return;
    const note = this.manualNote();
    this.manualResolve.emit({ logId: log.id, note: note.trim() || 'Đã xử lý tay bởi người vận hành.' });
    this.manualResolveOpen.set(false);
    this.manualNote.set('');
  }
}
